gigya_user_register:
    pattern:      /user/register
    defaults:     { _controller: GigyaBundle:Register:choose }
    requirements: { _method: get }

gigya_user_create:
    pattern:      /user/create
    defaults:     { _controller: GigyaBundle:Register:create }

gigya_user_link:
    pattern:      /user/link
    defaults:     { _controller: GigyaBundle:Register:link }
