gigya_user_register:
    pattern:      /user/register-by-email
    defaults:     { _controller: GigyaBundle:Example:registerByEmail }

gigya_account:
    pattern:      /user/account
    defaults:     { _controller: GigyaBundle:Example:account }
